Second task: user interaction
AndreyShpakXB/webix-start pull request #2
Opened 2021-09-23 19:11 UTC by AndreyShpakXB

Popup shows after clicking button "Profile"
Now you can add new movie. Entered data validates and if validation function returns true then item adds to table, else shows error message.
In addition i updated footer align (instead of align{ ... } i setup text-align using css)

2021-09-23 19:59 UTC, VeraOrekhXB requested changes

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/main.js
> +function clearForm() {
У тебя везде именуются функции с помощью нижнего подчёркивания, а тут camel case
Лучше использовать что-то одно
Обычно используют camel case

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/main.js
> +        year:function(val) { return val > 1970 && val <= new Date().getFullYear(); },
Обычно если нужно написать функцию в одну строку, используют стрелочные функции
Так код легче читается

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/main.js
> +    form.setValues({});
У формы есть метод clear

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/testdata.js
>  var small_film_set = [
Лучше данные и логику разнести в разные папки

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/main.js
> +        function() {
Если при нажатии на кнопку 'Cancel' ничего не должно происходить, то данную функцию можно опустить и оставить только одну первую

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/main.js
> +        let movie = form.getValues();
Значение не меняется, поэтому лучше использовать const

2021-09-23 19:59 UTC, VeraOrekhXB commented on js/main.js
> +        rating:function(val) { return val != 0;  },
Если ввести строку любую, то валидация пройдёт
Хотя в условии сказано, что значение не должно быть пустым или равным нулю, но не то, что значение должно быть числовым
Но судя по тестовым данным, скорее всего подразумевается число
@HelgaListopad, данное поведение является верным или значение рейтинга всегда должно быть числовым?

2021-09-23 20:41 UTC, AndreyShpakXB commented on js/main.js
> +        year:function(val) { return val > 1970 && val <= new Date().getFullYear(); },
исправил

2021-09-23 20:41 UTC, AndreyShpakXB commented on js/main.js
> +    form.setValues({});
исправил

2021-09-23 20:41 UTC, AndreyShpakXB commented on js/testdata.js
>  var small_film_set = [
исправил

2021-09-23 20:41 UTC, AndreyShpakXB commented on js/main.js
> +        function() {
исправил

2021-09-23 20:41 UTC, AndreyShpakXB commented on js/main.js
> +        let movie = form.getValues();
исправил

2021-09-23 20:42 UTC, AndreyShpakXB commented on js/main.js
> +        rating:function(val) { return val != 0;  },
валидацию на число в Rating сделал, текстовое поле Title защитил с помощью регулярки от ввода тегов.

2021-09-23 20:51 UTC, VeraOrekhXB requested changes

2021-09-23 20:51 UTC, VeraOrekhXB commented on js/main.js
> +    return ;
Для чего нужна эта пустая функция?

2021-09-23 20:56 UTC, AndreyShpakXB commented on js/main.js
> +    return ;
забыл убрать, уже исправил

2021-09-24 08:23 UTC, VeraOrekhXB approved these changes

2021-09-24 10:49 UTC, HelgaListopad approved these changes

2021-09-24 11:27 UTC, merged